### ISSUE TITLE
Generate workspace summary per category

### ISSUE THREAD

**Issue by theherk** [nvim-neorg/neorg#1086]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

It would be pretty slick if the command took an argument. For example, `:Neorg generate-workspace-summary some-category`, then populate the files where metadata is found to match. I wonder if this could be done somehow in relation to #967, where you could set up ranges per category, and populate with the applicable summary data.

### Help

Yes

### Implementation help

I'm confident the work to be done is within core/summary/module.lua, but I'm unclear how the invocation of `add_commands_from_table` sets up the command to accept an additional argument in the command. I would need a lot of direction to be of much help.

**Comment by Dynge** [comment]
I think this feature would be really neat.

I've taking a look at how one could implement it. I found that it seems to be rather simple to get it working with a few tweaks (see screenshot for git diff in my test)
![image](https://github.com/nvim-neorg/neorg/assets/25584899/50469d58-34e2-4034-9607-5c91799f672e)

However sadly the method to call generate-workspace-summary is not public and I am not sure how to tweak and edit `Neorg` commands. So I unsure how to complete the final step as you (@theherk) mentioned as well :)

I think it would be neat if the lua function is made public in the module such that one could send a list of categories to summarize (as suggested in my screenshot). I thought about making the `Neorg` command also accept a list of strings, however since categories are split by newline and NOT by space, then I dont see how the `Neorg` command would know how to differentiate categories:

eg. `Neorg generate-workspace-summary awesome tiger` - is this a single category (`awesome tiger`) or is it two categories (`awesome` and `tiger`)?

**Comment by Dynge** [comment]
Added a pull request for a suggestion to a potential solution: see #1156
