### ISSUE TITLE
Add alphaordered lists

### ISSUE THREAD

**Issue by top4ek** [nvim-neorg/neorg#1088]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

Now we have ordered lists (~) and unordered (-). Can alphaordered lists be added like following?

A. item one 
B. item two
C. item three
D. item last

### Help

No

**Comment by max397574** [comment]
if the latter then this can already be accomplished by changing the config

**Comment by max397574** [comment]
well it's possible to change the concealer config so ordered lists are rendered like this
tbh I don't see a usecase in adding this but not my decision 🤷‍♂️ 
and I'm not sure if we even have any characters left tbh

**Comment by vhyrro** [comment]
Hey! The way I see it is as follows:

"Alphaordered" lists are simply derivations on the general "ordered" list (they represent order in a list), and as such the `~` suffices, you can simply just modify the concealer to display alphaordered list items instead. They are semantically indifferent, which is why making another syntax element for it makes no sense from our standpoint. Besides, we are essentially out of new characters for syntax, so we have to use our syntax sparingly :)

As for the `A. item one` syntax, that's also not possible. I go in depth into those syntax decisions [here](https://github.com/nvim-neorg/norg-specs/issues/19#issuecomment-1625520953) in case you were curious!
