### ISSUE TITLE
Do not change undo history when auto updating metadata

### ISSUE THREAD

**Issue by champignoom** [nvim-neorg/neorg#1112]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

Normally, `u` followed by `<ctrl-r>` should be a no-op.

But if I save the file in between, that is `u` then `:w` then `<ctrl-r>`, the saving action modifies the timestamp and creates a new undo branch, which prevents redo.

It would be nice if the undo status can somehow remain unaffected upon saving.

### Help

Yes

**Comment by max397574** [comment]
if  we'd just set `vim.o.ul=vim.o.ul` that'll create a new "undo break" or however you want to call that. Then you can undo the change and switch to a different undo branch (idk how but somehow it's possible in vanilla, otherwise use e.g. undotree.vim) and  you're able to redo the change.

**Comment by champignoom** [comment]
Never mind. We just have to replace `<ctrl-r>` with `g-`, so `u` then `:w` then `g-` does the job.

**Comment by kflak** [comment]
Not sure if this is even the same issue, but using metadata makes undo unusable for me... It only happens when the `updated` field exists, otherwise no problem.

https://github.com/nvim-neorg/neorg/assets/13571232/fd339c74-448d-403a-a961-85e69f535706

System:
Arch linux latest,
❯ nvim -v
NVIM v0.10.0-dev-741+g996dd36c77
Build type: RelWithDebInfo
LuaJIT 2.1.1702233742
Run "nvim -V1 -v" for more info

Neorg commit:  5432be2

Best, and thanks for an awesom plugin!

**Comment by benlubas** [comment]
@kflak this is b/c you have an autosave plugin. I use one too, just spent a little time solving it. but the way that I went about doing it seems like a hack, and requires that you remap your `u`/`<c-r>` keys for the best experience. see the PR that just got linked.

**Comment by kflak** [comment]
aaaah... makes sense! Had similar issues with autosave and Oil.nvim now that you mention it. Thanks for the PR!
