### ISSUE TITLE
[keybinds] docs: indicate alternative reference to leader key

### ISSUE THREAD

**Issue by thenbe** [nvim-neorg/neorg#1115]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

I faced a very minor issue while trying to unbind a neorg key for the first time.

I was trying to unbind a single key:

1. First, I tried the first 3 statements shown below (marked "NOT OK") - none of which worked.
2. I [searched](https://github.com/search?type=code&q=path%3A*.lua+keybinds.unmap) for other examples to see if I was doing something out of the ordinary, but they were doing the same thing as me.
3. Looked at the source code, and copied the `keybinds.leader .. "nn"` line. This worked.

```lua
["core.keybinds"] = {
  config = {
    hook = function(keybinds)
      keybinds.unmap("norg", "n", "<Space>nn") -- NOT OK
      keybinds.unmap("norg", "n", "<space>nn") -- NOT OK
      keybinds.unmap("norg", "n", "<leader>nn") -- NOT OK

      keybinds.unmap("norg", "n", keybinds.leader .. "nn") -- OK
      -- print(keybinds.leader) -- "<LocalLeader>"
    end,
  },
}
```

## Expected

Some of the first three statements to unbind the key. Especially since my leader and localleader are identical (see below).

## Actual

Had to explicitly specify `<LocalLeader>` or `keybinds.leader`

## Possible Solutions

- Add a note in the docs to tell users to use `keybinds.leader .. "nn"` syntax. (Preferred because DRY)
- Add a note in the docs to tell users to use `<LocalLeader>nn` syntax.
- Others?

### Config

```lua
-- start of init.lua, before any plugins are loaded
vim.g.mapleader = " "
vim.g.maplocalleader = " "
```

### Versions

neorg: `969b3f1`

```bash
$ nvim --version

NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1693350652
```

### Help

Yes

**Comment by max397574** [comment]
🤔 this is weird
I think `" ".."nn"` (without the `..`, those were just to make clear that a space was used) should work as well because that's what the leader variable(s) are set to. Therefor I'd kinda expect the first three options not to work. But it's really weird that the final one actually worked.
😬 I'm not at home right now so I can't test. It would be really cool if you could also test with a literal space (perhaps with different localleader and leader keys as well...) 🙏 
But no matter what the results of the test would documentation should definitely improved. If you want to help with this I think you should change the comment at the beginning of the module since most of the wiki is autogenerated (I hope this part is as well xD otherwise you could copy it to the appropriate place)
As far as I know (and I also hope so) we'll eventually rewrite this anyway because it's really ugly.

**Comment by thenbe** [comment]
I tested a few more cases, including a literal space. Here are the results:

```lua
-- LEGEND:
-- OK: keybind is unnmapped successfully
-- NOT OK: keybind is not unmapped

keybinds.unmap("norg", "n", keybinds.leader .. "nn") -- OK
keybinds.unmap("norg", "n", "<LocalLeader>" .. "nn") -- OK
keybinds.unmap("norg", "n", "<Localleader>" .. "nn") -- NOT OK
keybinds.unmap("norg", "n", "<localleader>" .. "nn") -- NOT OK
keybinds.unmap("norg", "n", "<leader>" .. "nn")      -- NOT OK
keybinds.unmap("norg", "n", "<Leader>" .. "nn")      -- NOT OK
keybinds.unmap("norg", "n", " " .. "nn")             -- NOT OK
```

It's not really a big deal - once you know that the first syntax (keybinds.leader .. "nn") is the one that works, the `unmap` function then works as expected. This why I think a simple mention in the docs is enough to close this.
