### ISSUE TITLE
High Level User Overview

### ISSUE THREAD

**Issue by TheCedarPrince** [nvim-neorg/neorg#14]
Hey @vhyrro - this looks great! I would love to try it out at some point. However, I have a system in place that I am quite comfortable with. Before I want to dive too much into the documentation of `neorg`, would there be any way you could make a high level user overview video showing how the day to day person might use `neorg`? Something like this video would be outstanding: https://www.youtube.com/watch?v=SzA2YODtgK4

Thanks!

**Comment by vhyrro** [comment]
Thank you! Of course, creating a tutorial is incredibly important for adoption. The thing is I want to wait a bit longer so that we build out on features. It would be a bit hard to create an overview without a lot to talk about and explain. I might either convert this to a discussion or keep this issue open here as a reminder in case I forget. I'm still kinda new to the github stuff so idk what exactly counts as a discussion and what doesn't lol

**Comment by vhyrro** [comment]
Pinned the issue, I think that's the right thing to do in this case

**Comment by TheCedarPrince** [comment]
Haha, no problem friend! In that case, I agree before about waiting for a video. The gifs are certainly great. However, maybe instead of a video I would love to just see maybe one gif (while you are building out features) of actually creating a `neorg` note. How everything comes together - that is not clear to me. But either way, I look forward to seeing this project built out more!

**Comment by molleweide** [comment]
hey I think that it would be great also if there was a file called `docs/EXAMPLE.norg` where you'd have a full example project that was sketched out in .norg format so that one can instantly just start reading through the syntax as a newbie. or multiple ones would be nice. If you have time to do that also it would be great.

**Comment by vhyrro** [comment]
@molleweide the reason for that is probably because there's a lot of changes happening constantly and changing the spec every single time to match would be very time consuming :)

I agree, adding a example.norg file sounds cool. I'll get to work on that eventually.

**Comment by mrossinek** [comment]
Be sure to checkout the [self-documenting example](https://github.com/nvim-neorg/neorg/blob/main/doc/neorg.norg) or try `:help neorg` after installing it!

**Comment by erwin** [comment]
Thank you @mrossinek ... This note would be very helpful prominently in the neorg README...
I went through a few pages before I found that and it answered all my questions.

**Comment by danymat** [comment]
Hello, we changed a lot of docs since then:
- You can check out the auto generated Wiki
- And the Readme Re-write currently on hold: https://github.com/nvim-neorg/neorg/tree/rewrite-readme

**Comment by ZBQtesla** [comment]
@danymat The [showcase](https://github.com/nvim-neorg/neorg/tree/rewrite-readme#-showcase) in [rewrite-readme](https://github.com/nvim-neorg/neorg/tree/rewrite-readme) is fantastic!!! Thank you for showing the great power of neorg. Love it sooooo much!

**Comment by danymat** [comment]
I close this issue as Documentation is vastly improved.
We plan to create videos showcasing neorg, but that'll be part of another feature.
Thanks everyone.

**Comment by pianocomposer321** [comment]
Hey, I know this is closed, but I'm not sure where else to ask this.

Now that 1.0 is out, is there a roadmap for video tutorials/overviews? I'm curretly using orgmode from within neovim, but I'm really interested in what a neorg workflow might look like instead. If it works out, I may even be interested in tinkering around with making a mobile app for it, as that would be necessary for my workflow.

Thanks for all your hard work so far!
