### ISSUE TITLE
Fix inline Latex rendering

### ISSUE THREAD

**Issue by glyh** [nvim-neorg/neorg#1442]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.10.0 Build type: Release LuaJIT 2.1.1713773202 Run "nvim -V1 -v" for more info

### Neorg setup

```lua
      require("neorg").setup {
        load = {
          ["core.defaults"] = {},
          ["core.export"] = {},
          ["core.export.markdown"] = {},
          ["core.concealer"] = {},
          ["core.completion"] = {
            config = {
              engine = "nvim-cmp",
            },
          },
          ["core.dirman"] = {
            config = {
              workspaces = {
                notes = "~/Documents/notes/neorg",
              },
              default_workspace = "notes",
            },
          },
          ["core.integrations.image"] = {},
          ["core.latex.renderer"] = {},
        },
      }

```

### Actual behavior

![image](https://github.com/nvim-neorg/neorg/assets/12870742/e7274fcf-eb4a-4c03-8079-f1eeb9720a6d)

### Expected behavior

1. Source is hidden when the formula is rendered
2. Have the formula using corresponding colors, if it's inside some text then the formula should be rendered using text's color. If it's inside a title, it should be rendered with a title's color.
3. The around text is aligned so that there's not a lot of space between the formula and the adjacent text. 
4. The rendered Latex takes care of line breaks. When the formula is rendered in 2 lines the issue is resolved automagically like in markdown.
```markdown
I can use $\LaTeX\\ like \\ this$, and it works 
```
![image](https://github.com/nvim-neorg/neorg/assets/12870742/6421f989-6527-45c6-b77e-0a4e8ad8262c)

6. for a single line of latex, if it exceeded the right end of the editor it should be rendered in the next line.
7. For now it seems that for latex formula to render correctly, all forward slashes should be double quoted. Is there a point for that or is that a bug?

### Steps to reproduce

Follow the [cookbook](https://github.com/nvim-neorg/neorg/wiki/Cookbook) with latex support. 

### Potentially conflicting plugins

image.nvim? 

### Other information

None.

### Help

Yes, but I don't know how to start. I would need guidance (check question below)

**Comment by glyh** [comment]
I don't know if it's related to #1438

**Comment by glyh** [comment]
I personally tends toward a typst support instead of latex, though.

**Comment by benlubas** [comment]
> I don't know if it's related to #1438, it seems not?

it's not. that PR is to fix a single issue. You're asking for a bunch of new features it seems like

---

> Source is hidden when the formula is rendered

This already works. and is the default, you probably don't have conceallevel set properly.

> Have the formula using corresponding colors, if it's inside some text then the formula should be rendered using text's color. If it's inside a title, it should be rendered with a title's color.

Well then I guess you expect the math to always be blue? That's how math displays when it's in headers, or bolded, or anything really. I also think this would be an additional performance hit for no real gain.

<img width="428" alt="image" src="https://github.com/nvim-neorg/neorg/assets/56943754/cfcb571a-529f-4bb8-83c7-7503e3526add">

<img width="428" alt="image" src="https://github.com/nvim-neorg/neorg/assets/56943754/c537eab5-c443-4886-bfb4-30e91ff15717">

> The around text is aligned so that there's not a lot of space between the formula and the adjacent text.

wdym? text is concealed so there is _no_ additional space between the image and the adjacent text. This might be a misunderstanding related to the conceallevel issue at the top of this list.

> The rendered Latex takes care of line breaks. When the formula is rendered in 2 lines the issue is resolved automagically like in markdown.

This is a lot harder than you think it is. It would be really hacky in the current implementation, let alone the upcoming one which will support typst.

> for a single line of latex, if it exceeded the right end of the editor it should be rendered in the next line.

Near impossible with the current implementation due to how much work image.nvim is doing for us.

> For now it seems that for latex formula to render correctly, all forward slashes should be double quoted. Is there a point for that or is that a bug?

not a bug, `\` is the escape char in the norg file format. So typing `\$` will produce a `$` in norg. (This is easy to see when you have the concealer turned on btw). So `\\` is needed to produce a `\`. I recommend using this syntax: `$| \frac{1}{2} |$` where everything between the `|` is verbatim.

---

typst support is around the corner

**Comment by glyh** [comment]
Also I guess I'll split this into separte feature requests for what makes sense.

**Comment by benlubas** [comment]
@glyh to make sure you see that
