### ISSUE TITLE
[BUG] prev_named_sibling

### ISSUE THREAD

**Issue by tex** [nvim-neorg/neorg#152]
### Contributions

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)

### Plugin Version

- [X] I am using the latest version of the plugin

### Neovim Version

- [X] I am using either 0.5 stable or the latest compiled 0.6 version

### Neovim Version

0.5.1

### Branch

master

### Loaded modules

default

### Expected behavior

Not error when opening EXAMPLE.norg

### Actual behavior

Error when opened EXAMPLE.norg

https://imgur.com/d13GyHG.png

**Comment by tex** [comment]
Great :) What version do you use?

**Comment by vhyrro** [comment]
I use the latest compiled version of neovim so i have all the latest goodies lol

**Comment by vhyrro** [comment]
Yo, just letting ya know that in `unstable` this has been fully fixed, ordered list concealing will automatically be enabled when Neovim 0.6 is being ran. We can't really merge that individual commit into `main` I'm afraid so main users are gonna have to wait it out a bit until we decide to merge the two branches. That may take a while though as I'd like to stabilize GTD before we perform any sort of merge :)

I'll close down the issue for now if that's alright since there's not much else to say in regards to it, as always anyone can bump if need be.
