### ISSUE TITLE
Update Link Format

### ISSUE THREAD

**Issue by mrossinek** [nvim-neorg/neorg#160]
### Discussed in https://github.com/nvim-neorg/neorg/discussions/125

<div type='discussions-op-text'>

<sup>Originally posted by **andreicorpo** September 21, 2021</sup>
Let's say I have the following structure

```sh
notes/
    index.norg
    test.norg
```

What should I add in `index.norg` to have a link to `test.norg` when I press `<CR>`?

I have tried the following and they don't seem to work:
`[test](test.norg)`
`[test](/test.norg)`
`[test](./test.norg)`

Also, after I run `Neorg` from a non `.norg` file with no arguments the first time it works - it takes me to my setup workspace. But after I run `Neorg return` and I go back, when I run `Neorg`,  I get
```
E471: Argument required
```
Does anyone have an idea why?</div>

We want to apply a few updates to our link format:
- **drop** support for including multiple files within the link target
- **add** support for pure file links (i.e. no inner-file target like a heading or marker, just a plain path)

**Comment by benfleis** [comment]
Another request/thought -- have you considered adding [external] workspace names to links?

In my growing scenario I have 3 workspaces (which live in different places on filesystem for _reasons_):
- work journal (daily notes & TODOs)
- notes (general, wiki-ish, projects, etc.)
- personal journal

I'd love to be able to link between them without having to know the full file path, but instead leverage the named workspace abstraction, a la a TODO item link `[Finish ProjectThing](::notes:ProjectThing:*Remaining Items)`

I could of course consider re-org-ing under a single path, and using soft links to categorize, but that has other implications for me, since each workspace has different expectations around sharing, etc.

**Comment by vhyrro** [comment]
There is a part of syntax that allows this behaviour - it's currently only implemented in the `new-links` branch tho, which I don't recommend touching unless you're ok with getting your hands a little dirty :P

It would look like this:
```
[text](:$my_workspace/location:*Location)
```

However note that we'll be changing the way links even work in the format (since we found several flaws in the markdown version). This means that the new version will look like this:
```
{:$my_workspace/location:* Location}[text]
```

Hope that clears things up :)

**Comment by vhyrro** [comment]
We'll be sure to let people know of the migration process ahead of time. We've changed quite a few syntax elements to make the norg format more predictable over the past few weeks. You won't randomly see your links just break one day lol

**Comment by danymat** [comment]
Closing this as we merged it into `main` ! If you want to see the changes, just run `:Neorg news breaking_changes`
