### ISSUE TITLE
A format for question and answers as well as mcqs

### ISSUE THREAD

**Issue by zim0369** [nvim-neorg/neorg#232]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

Question and answers and MCQs are an important format of note taking. 
Writing Question and answers as well as MCQs in neorg is not a problem except for single correct MCQs.

Is there a way to have MCQs format in which only one option can be ticked?
Using ○ for unmarked options and ◉ marked but only one can be marked.

If this makes sense then a better version of this would be to have a checker that also checks the MCQs for right and wrong answers with a total score. 

### Help

No

**Comment by danymat** [comment]
Hello !

Neorg does not support this feature at the moment, but this capability could easily be created with a module. maybe something like this:

```
#only_one_answer
* Question: ...

- [ ] option 1

#correct_answer
- [ ] option 2

- [ ] option 3
```

**Comment by vhyrro** [comment]
That's possible, mrossinek and I will also discuss that potential of this being a syntax element too later today :)
MCQs aren't something I've ever taken into consideration, so this is gonna be interesting. If we ever come to a conclusion I'll be sure to let y'all know here.

**Comment by zim0369** [comment]
@vhyrro  Thank you so much!

**Comment by vhyrro** [comment]
Welp, this just autoclosed without me realizing oops

We've managed to figure out a nice syntax related to this (which isn't overly complex), and will be detailing it in our [formal specification](https://github.com/nvim-neorg/tree-sitter-norg/blob/dev/docs/NFF-0.1-spec.norg).
The reason I'm not detailing it here is because it would take a lot of time 😅, especially since we've made other mini-syntax changes inbetween that I'd have to also explain in order to explain this syntax. The TL;DR though is that you will be able to use a carryover tag (`#choice` in the current syntax, will be changed in the final specification to `|choice`), to convert a regular list into an MCQ or single-choice question. You can see the developer notes [here](https://github.com/nvim-neorg/dev-notes/blob/main/syntax/multiple-choice-questions/final-ideas.norg) if you want just a little more insight.

That's only the syntax, but we also have ideas for 0.2/0.3 that will make managing multiple choice questions much much easier :P

Once again sorry for that abrupt issue close!
