### ISSUE TITLE
Orgdown support

### ISSUE THREAD

**Issue by crepererum** [nvim-neorg/neorg#322]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

I'm wondering if it might be possible to support [orgdown](https://gitlab.com/publicvoit/orgdown/-/tree/master). IMHO it would be nice to have a common standard for org files, because it increases the chance that files are still usable in the future (e.g. in case neovim will be replaced by something different). 

### Help

No

**Comment by vhyrro** [comment]
Hey! Sorry for the incredibly late response.

Supporting anything *other* than Neorg's format isn't quite in our scope here - just like it isn't in org-mode's scope to support markdown.

Orgdown is an interesting and respectable attempt of standardizing org, however in our eyes isn't the format to go with. Since it's derived from org it carries some of the same baggage and problems that we worked so hard on fixing in `.norg`.

With enough dedication from the community it may very well be possible to support other formats than .norg, but it'd be very difficult, essentially requiring a complete rewrite of many core modules in order to work.

Hope that answers your question!

**Comment by crepererum** [comment]
That answers my question, thank you!
