### ISSUE TITLE
Video tutorial

### ISSUE THREAD

**Issue by MyraBaba** [nvim-neorg/neorg#449]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

Hi,

For the newbies there should be a video tutorial to show how to use ang get benefit from the neorg. Really

### Help

No

### Implementation help

a real life example covering keyboard shortcut and showing the screen

**Comment by max397574** [comment]
this is planned for the 0.1 release

**Comment by aatmasaat** [comment]
and when will 0.1 be ready?

**Comment by vhyrro** [comment]
Things have changed a little bit since then - the video tutorial will be ready once the **1.0** release of the *file format* is ready. We were going to release the file format's 1.0 version sooner, but then we found a last minute issue regarding macros and decided to rewrite them entirely :joy: 

There are a few things left to discuss, including some edge cases and whether variables are really needed (since macros can do the same thing). As soon as we get a release candidate you can expect a reddit post :)

**Comment by mhrshi-paanini** [comment]
thank you, looking forward to the tutorial :)

**Comment by vhyrro** [comment]
Found this issue while scrolling around again :p 

Two parts of the series are already available [on youtube](https://www.youtube.com/watch?v=NnmRVY22Lq8&list=PLx2ksyallYzVI8CN1JMXhEf62j2AijeDa), with a third coming up!
