### ISSUE TITLE
Error Executing lua callback error whenever currently on codeblock completion in cmp 

### ISSUE THREAD

**Issue by siduck** [nvim-neorg/neorg#571]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

NVIM v0.8.0-dev-1025-gfb39bba5a
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-10 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE
-DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/cmake.config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az177-947

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info

### Neorg setup

```lua
  require('neorg').setup { load = {
    ["core.norg.concealer"] = {},
  } }
```

### Actual behavior

![image](https://user-images.githubusercontent.com/59060246/188637037-0ce2de97-09df-4f26-a34e-b69653be7f4a.png)

### Expected behavior

dont get that error

### Steps to reproduce

use the above neorg config ( make sure cmp is lazyloaded at insertEnter )

### Help

No

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/188639351-6cf11746-4de5-45a3-af3e-e993372b2a5c.mp4

removing concealer module fixes the issue

**Comment by siduck** [comment]
Idk what happened to the treesitter parsers of neorg, I can no longer use them anymore :disappointed: 

![image](https://user-images.githubusercontent.com/59060246/190937150-233b9d72-f617-43c9-ab25-c10eeb1a49c9.png)

**Comment by siduck** [comment]
i thought at least the 0.0.12 tag was working as mentioned in the readme

**Comment by siduck** [comment]
@vhyrro @max397574 so neorg now works only for 0.8?

**Comment by vhyrro** [comment]
In such case please be my guest. I'm not a machine.

**Comment by siduck** [comment]
> In such case please be my guest. I'm not a machine.

I even pmmed you on discord a month ago regarding my other issue but got no reply but I see you talking in the your server, couldve at least told that you dont have much time to reply or dont want to help. its just feels bad to get ignored and I waited for nothing! 

That wasnt much of a big issue as it happened only for the codeblock but today neorg was completely unusable on 0.7.2, I was assured that it would work with the older tag as mentioned in the readme.

I was supposed to show my private repo ( filled with important notes & journals written in norg files ) to someone really important to me and then neorg suddenly breaks & is completely un-usable unless I use nightly.  And Ive to use stable nvim only for some reasons.  

And my whole day was ruined! This was my most favorite neovim plugin. Really sorry about the comment earlier, I got too frustrated.

**Comment by vhyrro** [comment]
Breakages can be annoying - I understand. I can see why the anger bubbled up. The fact is I realized that I couldn't pinpoint the cmp error, and the error was highly ambiguous with no indication on what the issue could be; I didn't notify you about it. That's my bad, sorry for that! To be completely honest I kind of hoped someone with more cmp knowledge would come along and say "aha! this is what you gotta do to fix it", but that didn't happen. 

`0.0.12` breaking is a separate issue and I'm pretty certain I know what the problem is - I also have a permanent fix in mind to prevent these sorts of errors from happening in the future. The TS parser changed some things and while main was fixed to reflect the changes, `0.0.12` was not. I'm a lazy mofo so of course I forgot to update the older version.

Each version will have its own pinned revision of the parser from now on. Give me just a few minutes and I'll follow up with a message! Also, it's safe to reopen this issue, and I do hope that someone comes along and helps out, as I have no clue what's going on. I should work on transparency when i *don't know* how to fix a problem - in the `self_improvement.norg` file it goes :p

**Comment by siduck** [comment]
nvm it now, it'll be a waste of time for you :/ . I've stopped using neorg now and wont use any other alternatives/webapps either. Really appreciate all of your work tho, I'd financially fund the project but i'm beyond broke & family with debts. 

You werent able to help me when I needed you the most :(( , its all over now as the damage here has been done ( cant explain it to you ). Good luck with the plugin!

**Comment by vhyrro** [comment]
Alright, have a good one. The 0.0.12 issue should be fixed now (for anyone else reading this, for whatever reason).
