### ISSUE TITLE
[Suggestion] API for moving to next/previous link in buffer

### ISSUE THREAD

**Issue by owenpearson** [nvim-neorg/neorg#579]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

This is a feature I use a lot in vimwiki. It would probably make sense to add the same api for other markup elements (jump to next code block, etc).

### Help

Yes, but I don't know how to start. I would need guidance

**Comment by Thlr** [comment]
I would love that as well.

Currently I use Ctrl-O to jump back to my index, which works right now because my file 'structure' is only one level deep. But I can see how it's going to be problematic for people who like to have a structure that's more vertical than horizontal.

Alternatives :
- Ctrl-O / Ctrl-I
- Writing a link back to the closest top-level file at the top of each page
- [harpoon](https://github.com/ThePrimeagen/harpoon)

All of these alternatives are not satisfactory in this context.

**Comment by max397574** [comment]
this is already implemented

**Comment by vhyrro** [comment]
Since this has been implemented I think it's safe to close now :)
