### ISSUE TITLE
Conflict with 'rmagatti/auto-session' when restoring sessions

### ISSUE THREAD

**Issue by igorlfs** [nvim-neorg/neorg#599]
### Prerequisites

- [X] I am using either 0.7 stable with the `0.0.12` tag or the latest compiled Neovim version
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.8.0-dev-1194-ga80ab395aa

### Neorg setup

```lua
require("neorg").setup({
    load = {
        ["core.defaults"] = {},
    },
})
```

### Actual behavior

Neovim throws an error:
```
Error executing vim.schedule lua callback: .../neorg/lua/neorg/modules/core/syntax/module.lua:191
: Invalid buffer id: 1                                                                                    
stack traceback:                                                                                          
        [C]: in function 'nvim_buf_get_name'                                                              
        .../neorg/lua/neorg/modules/core/syntax/module.lua:191: in function 'trigger_highlight_re
gex_code_block'                                                                                           
        .../neorg/lua/neorg/modules/core/syntax/module.lua:634: in function 'on_event'           
        .../neorg/lua/neorg/events.lua:153: in function <.../neorg/lua/neorg/events.lua:140>
```

### Expected behavior

No error is thrown.

### Steps to reproduce

1. Install 'rmagatti/auto-session' 
2. Open a file and use `:SaveSession`
3. Quit vim and execute it again without arguments (to trigger auto-session). The error will be thrown.

### Potentially conflicting plugins

Definitely 'rmagatti/auto-session' 

### Help

No

**Comment by griffinwxk** [comment]
Can confirm the issue with nvim 0.8 and auto-session. Any fix yet?

**Comment by fnune** [comment]
Seeing the same problem here!

**Comment by sergiornelas** [comment]
As a temporary solution I disabled the core.defaults in order to prevent that prompt message at starting neovim
		```
-- ["core.defaults"] = {},
		["core.norg.esupports.hop"] = {},
		["core.highlights"] = {},
		["core.mode"] = {},
		["core.neorgcmd"] = {},
		["core.integrations.treesitter"] = {},
		["core.norg.esupports.indent"] = {},
```

**Comment by aniketgm** [comment]
The issue seems to come with `["core.syntax"]`. I was not getting the error message after disabling it. Others are fine.
I'm not aware of lua language, but it seems the `trigger_highlight_regex_code_block` function exposed by the syntax module is causing the error for some event.

After trying to make sense on my own, (developers/contributors, correct me if I'm wrong) it seems the nvim_buf_get_name should get buffer Id as a string, but instead is getting buf as a number.

**Comment by katawful** [comment]
I'm the author of `core.syntax`, and I'm not seeing any reason why the module should fail, nor does it fail with startify or my custom startup solution. It looks like an error with the event module, but I am unaware as to how it could give invalid buffers

`core.syntax` is built very strangely in order to make it as seamless and not-awful as possible. Part of that requirement is not being able to schedule any part of that. The 2 session managers I have access to do not use any scheduling, so the only thing I can suggest is to poke around within 'auto-session'

**Comment by sergiornelas** [comment]
I don't have `core.syntax` loaded (neither `core.defaults`) and I still receive the error message.

**Comment by igorlfs** [comment]
Hey, this has been solved! Not sure if due to a modification with auto-session? Anyways, I'm not having the issue anymore.
