### ISSUE TITLE
[BUG] Rule wrongly exported to Markdown

### ISSUE THREAD

**Issue by anakojm** [nvim-neorg/neorg#719]
### Prerequisites

- [X] I am using either 0.7 stable with the `0.0.12` tag or the latest compiled Neovim version
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.9.0-dev-788+gf08051c2e

### Neorg setup

```lua
require('neorg').setup {
    load = {
        ["core.defaults"] = {},
        ["core.norg.dirman"] = {
            config = {
                workspaces = {
                    orga = "~/TODO/",
                }
            }
        },
        ["core.norg.concealer"] = {
            config = {
                icon_preset = "basic",
                markup_preset = "brave",
            }
        },
        ["core.export"] = {},
        ["external.context"] = {},
        ["core.export"] = {},
        ["core.export.markdown"] = {
            config = {
                extensions = "all",
            },
        },
        -- ["core.gtd.base"] = {
        --     config = {
        --     workspace = "orga"
        --     }
        -- }
    }
}
```

### Actual behavior

`bug.norg`:
```norg
___
```

`:Neorg export to-file bug.md` produces `bug.md`:
```markdown
```

### Expected behavior

`no_bug.norg`:
```norg
___
```

`:Neorg export to-file no_bug.md` produces `no_bug.md`:
```markdown
___
```

### Steps to reproduce

- Create a norg file with `___` inside.
- Run `:Neorg export to-file file.md`.
- Observe that the rule in `file.md` disappeared.
- Cry

### Help

No

**Comment by d-r-a-b** [comment]
This turns out to be a simple issue to fix and I'll submit a PR for it. I actually think this issue is a good reference issue for anyone to look at if they want to contribute back to the project and help out with fleshing out the exporter

Here is the basic stuff you need to know to hack on the markdown export:

1. Read https://github.com/nvim-neorg/neorg/blob/d61c4d1dd9442ec34d57e4a296b35a1117e65dbb/lua/neorg/modules/core/export/module.lua#L1-L27 for a concise overview of the overall export module.
2. The file is very well commented, but the meat of it is that you iterate through nodes, passing them to a "function" defined in the `format/module.lua`, e.g `export/markdown/module.lua`, which can be a string, a bool or an actual function. Semantics described at https://github.com/nvim-neorg/neorg/blob/d61c4d1dd9442ec34d57e4a296b35a1117e65dbb/lua/neorg/modules/core/export/module.lua#L134-L144
3. There is a concept of "recollectors" for when the norg syntax does things in a different order than the export syntax, so you need to somehow reorder things appropriately

Knowing this, I just had to add a `["horizontal_line"] = "___"` in `export/markdown/module.lua`. `true` is a bad idea because two underscores are enough to be a horizontal rule in norg, but not in Markdown. You could get fancy and give it a function that checks the length of the rule, increases it to 3 if necessary, or else outputs the same number as in the norg as well.
