### ISSUE TITLE
Ordered List Should Show Number but It Doesn't

### ISSUE THREAD

**Issue by sdifru** [nvim-neorg/neorg#840]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.9.0

### Neorg setup

```
{
	"nvim-neorg/neorg",
	event = "VeryLazy",
	build = ":Neorg sync-parsers",
	config = function()
    vim.opt.conceallevel = 2

    local neorg = require("neorg")
		neorg.setup({
			load = {
				["core.defaults"] = {},
				["core.concealer"] = {
					config = {
						folds = false,
            dim_code_blocks = {
              width = "content",
            }
					},
				},
				["core.dirman"] = {
					config = {
						workspaces = {
							notes = "~/neorg",
						},
						default_workspace = "notes",
					},
				},
				["core.export"] = {},
				["core.completion"] = { config = { engine = "nvim-cmp", name = "[Neorg]" } },
			},
		})
	end,
	dependencies = { { "nvim-lua/plenary.nvim" } },
}
```

### Actual behavior

It renders square
![2023-05-05_10-05-1683258958](https://user-images.githubusercontent.com/123437835/236375491-57f1c5ec-45a5-4cd1-ab3f-21174b004f46.jpg)

### Expected behavior

The square should be a number.

### Steps to reproduce

I use [wezterm](https://wezfurlong.org/wezterm/). Wezterm includes [fonts](https://wezfurlong.org/wezterm/config/fonts.html#font-related-configuration). I've used wezterm and neorg and there hasn't been any problem. Recently this problem occurs. Tbh I don't if it is wezterm, neorg, or something else.

### Help

None

**Comment by pysan3** [comment]
Recently we've got a major version release from nerd-font (v3.0.0) so it might be that the fonts on your system are too old.

Would that fix when you update your fonts?

**Comment by sdifru** [comment]
I searched for nerd fonts in the arch repo and it returned a lot of nerd fonts. Which one?

**Comment by sdifru** [comment]
I accidentally pressed close issue button, sorry.

**Comment by d-r-a-b** [comment]
@sdifru Hopefully someone will come by and chime in with what worked for them, but if it's really important to you, you could try and find one and report back what works for you? The Unicode code point starts at https://www.compart.com/en/unicode/U+2488.

It's hard to say what font/font versions exactly are going to be on every distribution. Honestly, I've just avoided these particular troublesome glyphs and configured my https://github.com/nvim-neorg/neorg/wiki/Concealer with

```lua
        ['core.concealer'] = {
          config = {
            icons = {
              ordered = {
                level_1 = {
                  icon = tostring,
                },
              },
              },
            },
          },
        }, -- Adds pretty icons to your documents
```

which uses the lua `tostring` function. Read more from the Wiki or dive into the implementation in https://github.com/nvim-neorg/neorg/blob/main/lua/neorg/modules/core/concealer/module.lua to understand more. You lose the dot after the number,  but you gain the ability to go past 20 since Unicode doesn't have any numbers after 20 for the style used in the default concealer preset.

**Comment by sdifru** [comment]
I've solved this problem. I installed noto-fonts and everything worked as expected.
