### ISSUE TITLE
Concealer module no longer started automatically after updating to 4.0.0

### ISSUE THREAD

**Issue by xfzv** [nvim-neorg/neorg#861]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.9.0 Build type: Release LuaJIT 2.1.0-beta3

### Neorg setup

```lua
{
		"nvim-neorg/neorg",
		ft = "norg",
		dependencies = { "nvim-treesitter/nvim-treesitter" },
		build = ":Neorg sync-parsers",
		config = function()
			require("neorg").setup({
				load = {
					["core.defaults"] = {},
					["core.clipboard"] = {},
					["core.clipboard.code-blocks"] = {},
					["core.completion"] = {
						config = {
							engine = "nvim-cmp",
						},
					},
					["core.concealer"] = {
						config = {
							dim_code_blocks = {
								enabled = true,
								conceal = true,
								content_only = true,
								adaptive = true,
							},
							icon_preset = "diamond",
						},
					},
				},
			})
		end,
	},
```

### Actual behavior

After updating to 4.0.0, the concealer module is no longer enabled automatically when opening a `.norg` file. I have to toggle it manually with `:Neorg toggle-concealer`.

Downgrading to 3.2.2 solves the issue.

### Expected behavior

The concealer module is loaded automatically.

### Steps to reproduce

1. Update Neorg to 4.0.0
2. Open a `.norg` file
3. The concealer module isn't loaded
4. Toggle it with `Neorg toggle-concealer`, all good
5. Downgrade Neorg to 3.2.2
6. Re-open any `.norg` file
7. The concealer module is doing its job without any manual intervention

### Help

No

**Comment by d-r-a-b** [comment]
Just a community member offering help. Consider trying `event = 'BufReadPre,BufNew *.norg'` and seeing what you get.

I'm not sure what the "correct" concealer behavior is supposed to be with regards to lazy loading , but this works for me. Try it out and please report back.

**Comment by Aumnescio** [comment]
I don't quite feel like this issue is solved. I am having issues with the the concealer and/or the whole of Neorg not lazy-loading properly.

It seems like the reason that the `event = 'BufReadPre,BufNew *.norg'` is "solving" this issue is that it does not actually lazy-load Neorg at all, which allows the concealer to load fine. I am not quite sure why the event is not doing what one might expect, but this event is activating even when entering non-norg files.

My issue is more specifically: "Lazy-loading Neorg is not working properly.", rather than a problem with the base concealer startup. However, when actually lazy-loading Neorg, the concealer will not start up properly.

Here is a minimal `init.lua` that I can reproduce these issues with:

``` lua
-- File:        `~/.config/nvim_minimal/init.lua`

-- NOTE: When using `NVIM_APPNAME=nvim_minimal` to launch into this alternate Neovim config,
-- this data path will not conflict with or pollute the primary data folders.
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"

-- Lazy Bootstrap:
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        "git",
        "clone",
        "--filter=blob:none",
        "https://github.com/folke/lazy.nvim.git",
        "--branch=stable", -- latest stable release
        lazypath,
    })
end

vim.opt.rtp:prepend(lazypath)

-- This is a dummy command which can be used as an event to lazy-load Neorg.
vim.api.nvim_create_user_command("StartNeorg", 'echo "Activating Neorg!"', {})

-- Lazy Setup:
require("lazy").setup({
    {
        "nvim-neorg/neorg",
        lazy = true,
        version = "*",
        -- event = "BufReadPre,BufNew *.norg",      -- This event does not lazy-load Neorg. ( But the concealer does activate in norg files. )
        -- event = "BufEnter *.norg",               -- This seems to cause issues with the concealer not activating.    ( But does lazy-load. )
        -- ft = "norg",                             -- This seems to cause issues with the concealer not activating.    ( But does lazy-load. )
        cmd = {                                     -- Even when lazy-loading using a command, the concealer will not activate.
            "StartNeorg",
            "Neorg",
        },
        build = ":Neorg sync-parsers",
        opts = {
            load = {
                ["core.defaults"] = {},
                ["core.concealer"] = {},
            },
        },
        dependencies = {
            "nvim-lua/plenary.nvim",
            "nvim-treesitter/nvim-treesitter",
        },
        config = function(_, opts)
            require("neorg").setup(opts)
            vim.api.nvim_create_user_command("StartNeorg", 'echo "Activating Neorg!"', {})
        end,
    },
})
```

To use this, place the file into `~/.config/nvim_minimal/init.lua` and start nvim using:

`NVIM_APPNAME=nvim_minimal nvim`

This keeps the minimal config/data folders separate from the user's main nvim config and data folders.

- NOTE: I think the `NVIM_APPNAME` feature does require a relatively recent version of Neovim. It works with the latest stable version. (v0.9.0)
