### ISSUE TITLE
Autoformat file

### ISSUE THREAD

**Issue by treeman** [nvim-neorg/neorg#874]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

I'm not sure if this is already possible or if this a feature request, but I'd like to format .norg files when saved.

For me this is super convenient and it's a good timesaver. For instance, sometimes the content under headings aren't indented correctly and now I need to indent them manually (visual selection with `=` works ok). Of course formatting is more than just indentation, this is just an example.

Is this possible somehow? Either with autocmd or something like [Neoformat](https://github.com/sbdchd/neoformat).

### Help

No

**Comment by katawful** [comment]
Indenting, which is most of the formatting needed, should be handled out of the box. You can check what the indent expression is set to with `:set indentexpr?`. It should be a neorg function, not a treesitter one

There is no norg formatter atm, but since indentation handles most of the formatting, `gg=G` will jump to the top of the file then indent down to the bottom

For line widths and style issues, you'll have to handle these manually. `gq` can format a paragraph to whatever the textwidth is set to

**Comment by d-r-a-b** [comment]
You can also set this up with a little vim knowledge. `:h autocmd` `:h BufWritePre`.

There are cases where this is harmful, i.e. if you have manual formatting that you don't want the indent engine to touch. An easy example is code blocks which do not have treesitter indent support (`:TSModuleInfo`). As such, it is not a good fit to implement this as part of Neorg in a non-robust way. My sense as a community observer is that other dev priorities are likely to be the primary focus for a while unless a contributor steps up.

**Comment by pysan3** [comment]
Found this. 

Maybe you can try it out?

https://github.com/nvim-neorg/norg-fmt

**Comment by CRAG666** [comment]
What are the formatting directives? I ask to configure.

**Comment by UtkarshVerma** [comment]
> > Found this.
> > Maybe you can try it out?
> > https://github.com/nvim-neorg/norg-fmt
> 
> That project isn't functional yet, it still has a long way to go before it's usable so the best solution for now is the native Neovim `gg=G` :p

That's a nice builtin method, but it does not play nicely with metadata. The categories are always pushed to the line beginning.

**Comment by leongjs98** [comment]
> > > Found this.
> > > Maybe you can try it out?
> > > https://github.com/nvim-neorg/norg-fmt
> > 
> > 
> > That project isn't functional yet, it still has a long way to go before it's usable so the best solution for now is the native Neovim `gg=G` :p
> 
> That's a nice builtin method, but it does not play nicely with metadata. The categories are always pushed to the line beginning.

do you still have this issue now on NVIM v0.9.2 with Neorg v6.0.0?

the built-in method `gg=G` shouldn't push the metadata categories to the start of the line now

should we close this old issue?

**Comment by pysan3** [comment]
> the built-in method gg=G shouldn't push the metadata categories to the start of the line now
> 
> should we close this old issue?

Yes, this method now works perfectly for almost all situation for me.

One last issue I have is in between `norg` code blocks. All indents in the code block gets shifted to the left.

-- Before `gg=G`
```txt
** Usage
*** Template Norg Files
    @code norg
    * {TITLE_INPUT}
      Weather: {WEATHER}
      {{:{YESTERDAY}:}}[Yesterday] - {{:{TOMORROW}:}}[Tomorrow]

    ** Daily Review
       - {CURSOR}
    @end
```

-- After `gg=G`
```txt
** Usage
*** Template Norg Files
    @code norg
    * {TITLE_INPUT}
    Weather: {WEATHER}                                            <- This line
    {{:{YESTERDAY}:}}[Yesterday] - {{:{TOMORROW}:}}[Tomorrow]     <- This line

    ** Daily Review
    - {CURSOR}                                                    <- This line
    @end

```

This issue does not happen on lua code block I only found this behavior in norg code blocks (tho I haven't tested for all).

This file is the one I'm having problem with.

https://github.com/pysan3/neorg-templates/blob/d96b4fbcb38223778696b48e3bf6e4e6a8a94ad8/README.norg#L39

**Comment by leongjs98** [comment]
I have just tested some other languages and these are the result on NVIM v0.9.2 with Neorg v6.0.0

| code | auto-format result |
|:---- |:------:|
| Bash | not working |
| Go | working |
| JavaScript | working |
| Lua | working |
| Norg | not working |

I believe we should close this issue and open another issue for this
Because this issue is mainly dealing with the code blocks whereas the original issue is general formating

"Auto-indent/format with `-` doesn't work with some code blocks"
@pysan3 what do you think this new issue title, if you think it's alright, let's just open a new issue and close this one

**Comment by pysan3** [comment]
Thanks @leongjs98 for testing!

> Auto-indent/format with `=` doesn't work with some code blocks

Nice title. Tho I believe you mistyped `-` with `=`.
Could you open the issue? I haven't got spare time now and don't have time to test it unfortunately.

**Comment by treeman** [comment]
I do not think this issue should be closed as it tracks a general formatter, not just indentation.

For example removing extra empty lines or formatting `authors: [ ... ]` into one or multiple lines depending on the count are some things a proper formatter should handle.

And besides that I think there are more things that auto-indent doesn't cover. I tried with [the 1.0 specification](https://github.com/nvim-neorg/norg-specs/blob/main/1.0-specification.norg) and it produces a fairly large diff. I'm not familiar enough withe neorg to pinpoint if all are valid or if the specification file itself isn't formatted correctly from the start, but do think there are some auto-indent issues with that file.

**Comment by leongjs98** [comment]
> Thanks @leongjs98 for testing!
> 
> > Auto-indent/format with `=` doesn't work with some code blocks
> 
> Nice title. Tho I believe you mistyped `=` with `-`. Could you open the issue? I haven't got spare time now and don't have time to test it unfortunately.

Yes, I mistyped. Thanks for spotting it!

will open a specific issue right away.

**Comment by leongjs98** [comment]
@treeman

> I do not think this issue should be closed as it tracks a general formatter, not just indentation.

My point of closing this issue is that it's hard to solve a problem when we don't know the specifics of the problem. And L

The example in the original issue:
> For instance, sometimes the content under headings aren't indented correctly and now I need to indent them manually (visual selection with = works ok).

is solved with the newer version of NeoVim and Neorg

Other than that, the original issue didn't have other specific formating issue. And the actual issues are scattered around in the comments. This just makes it harder for the developer to try to solve this.

Whilst the formater can definitely be improved, my suggestion is to open new issues with more specifics so it's easier to discuss and solve them.

**Comment by treeman** [comment]
> Other than that, the original issue didn't have other specific formating issue. And the actual issues are scattered around in the comments. This just makes it harder for the developer to try to solve this.

Good points! Closing this.
