### ISSUE TITLE
taskwarrior integration status

### ISSUE THREAD

**Issue by fecet** [nvim-neorg/neorg#876]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

I am a user of Taskwarrior, and I have been facing difficulties in integrating it into my Neovim workflow. I came across Neorg, which seems to be a promising solution. I noticed that @vhyrro mentioned its integration plans in the following GitHub issue: https://github.com/nvim-neorg/neorg/issues/11. I was wondering if there have been any updates regarding its current status. 

### Help

Yes, but I don't know how to start. I would need guidance

**Comment by d-r-a-b** [comment]
As an observer of the dev process and discussions happening in the discord, it appears that the main development priorities at the moment are on building key architectural components of Neorg, like the macro system, concealer performance, parsers, and databases that will undergird many of the workflow extension tools.

Any specific integration is only likely to see rapid development if a specific dev/contributor decides they need it and implements it. https://github.com/skbolton/neorg-taskwarrior looks like someone was working on a module to do this, but it does not look like it has had a commit in a while, suggesting that other life priorities diverted the author's ability to work on this.

If this integration is critical to you, feel free to contribute to the efforts in the other repo, roll your own integration strategy, pay someone to create an integration, find a taskwarrior vim plugin that works well with Neorg or use an alternative ecosystem until such functionality exists in Neorg. If it is not critical and you are still excited about the number of promising features already supported by Neorg and are excited about the philosphy and design of the norg syntax/Neorg plugin, welcome to the community!

**Comment by fecet** [comment]
Of course I'm willing to contribute but perhaps I should wait until neorg's GTD system is sufficiently developed? Can you guide me on how to start implementing such integration if I want to? Because it seems that currently, neorg only implements a simple todo items feature.

**Comment by SevorisDoe** [comment]
The neat thing about making some thoughts early is that your wishlists have a better chance of being accomodated. Those who move, move things. 

Plus, code is only part of the whole package. Motivations, problems, preliminary research, API proposals and constraints, all of that is valuable to making good software.

**Comment by d-r-a-b** [comment]
> Of course I'm willing to contribute but perhaps I should wait until neorg's GTD system is sufficiently developed?

If you want to wait, you can follow along in https://www.github.com/nvim-neorg/neorg/issues/695. The open source free labor timeline is tricky to estimate and prone to delays. I think the maintainer for that feature has been a bit busy of late and I'm not sure what thing in coding/life they are currently prioritizing.

I can't speak to what your available bandwidth or interest for this problem are, but the alternative to waiting on a blocker is to work on removing the blocker. If this is of interest, you could get in touch with the maintainer of that effort and see if they are open to collaboration and whether you have aligned visions for the feature scope/implementation? You could take the same approach with the other taskwarrior module that I linked.

> Can you guide me on how to start implementing such integration if I want to? Because it seems that currently, neorg only implements a simple todo items feature.

For now, I would advise looking over at https://github.com/andreadev-it/neorg-module-tutorials for guidance. The other big place to look is in the codebase, especially at `lua/neorg/modules/base.lua`. 

One thing I am working on (with the same timeline constraints) is a template for modules to make this easier. My efforts at producing a template are really just an extension of me working through how to put together a module and right now basically consist of just that `base.lua` file renamed and in the appropriate directory structure and associated documentation files that a module project should probably include. As a result, what (eventually) comes out of those efforts also probably shouldn't be taken as best practice, and instead just an example of a solution that worked for me, especially since I am more of a code hobbyist than a code professional.

> Motivations, problems, preliminary research, API proposals and constraints, all of that is valuable to making good software.

Yep, just for example, my most valuable contributions in this project to date are a document detailing setup dependencies and work towards thinking about a citation syntax for neorg. You could do something similar which will help shape the effort and make it easier for an implementor to see what the actual business requirements of an integration might look like. If you have really solid ideas for a nice workflow that would integrate Neorg + some tool, it's always nice for the community to hear those ideas and maybe you'll get someone with the skills + interest + time to put something together quickly. Iterating on ideas is cheap and talking about it helps make sure that everything plays nice with other modules. That could be done in association with the Neorg project, in the neorg discord, or in the taskwarrior module project I linked above. If that doesn't sound appealing, you can always roll your own implementation for your exact use case with no or limited discussion. Sharing that work back with the community would be optional but very generous and encouraged.

**Comment by SevorisDoe** [comment]
> Yep, just for example, my most valuable contributions in this project to date are a document detailing setup dependencies and work towards thinking about a citation syntax for neorg. You could do something similar which will help shape the effort and make it easier for an implementor to see what the actual business requirements of an integration might look like
Speaking personally, my main contributions right now are a lot of work in researching and evaluating problems and solutions for various background utilities needed for the native ecosystem - that effort has lead to things like Norgberg and Norgopolis as solutions for specific problems (and in specific ways). These all started from discussing problem sets at other applications and us steadily working our way through the issues at hand to find solutions. 

We are definitely not done finding problems and defining solutions for them. And speaking as someone currently architecturing around in the guts of future Neorg a fair lot - I would love to hear others tell us what kind of information they want to handle and how. That is valuable for defining the solutions that happen right now.

**Comment by benlubas** [comment]
Going to close this as it's gone off topic.

Generally an integration with task warrior is best suited for an external module anyway. If you're still interested, there's the above prior art as well as a guide for writing modules here: https://github.com/benlubas/neorg-module-tutorial

and the discord would be the best place to ask for further help!
