### ISSUE TITLE
add support for which-key.nvim

### ISSUE THREAD

**Issue by CRAG666** [nvim-neorg/neorg#889]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

It would be nice to add support, as it's easier to get to know the keys when you're not yet familiar with all the keymaps
https://github.com/folke/which-key.nvim

### Help

Yes

### Implementation help

I think I can implement it, just by adding description to the vim.keymap.set command

**Comment by snikoletopoulos** [comment]
That would be nice. The `:Neorg keybind` could show the same labels as well

**Comment by joshuanave** [comment]
Came here to look at this -- currently the which-key "sort of" works in that the "prefix" auto fill is put for buffer specific bindings for neorg. Inside of those the actual command is used as a description i assume because no desc tag is provided. I wouldn't mind helping with this but i actually don't know  lua or even where to start adding it.
