### ISSUE TITLE
[FEATURE REQUEST]  Writing configs , or even code , using neorg

### ISSUE THREAD

**Issue by LamprosPitsillos** [nvim-neorg/neorg#89]
### Issues

- [X] I have checked [existing issues](https://github.com/vhyrro/neorg/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

Would there be support for exporting the code segments to an actual file , like many emacs users do. They write well documented code in org and then just export it.
![Window_org](https://user-images.githubusercontent.com/61395246/131972487-d381c642-d6fa-429b-bfb3-b5998378c78c.png)

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

I read in the CONTRIBUTING.md that i have to write everything in `modules`. So i make a new dir in /modules and start hacking away? Any help would be appreciated !

**Comment by vhyrro** [comment]
We actually used to have tangling support for a short period of time but then had to scrap it because the implementation was "meh" at best. In the GTD branch Dany and I are working on a native query system for neorg which will allow us to extract info from files easily. It would be a lot more feasible to start implementing tangling after that's done being worked on :)

Since i expect the gtd stuff to be done roughly in a few weeks unfortunately that means you're going to have to wait a bit, we gotta go one step at a time. By all means tho if you still wanna help out you can read the Creating Modules page in the wiki and start a GitHub discussion where we can talk about the syntactical details and things

**Comment by danymat** [comment]
Hello, it seems like the queries native module is stable. Maybe we can check this issue again @vhyrro ?

**Comment by vhyrro** [comment]
Tangling has been moved to the last thing we'd like to do for 0.1, since there's so much else that had popped up recently. Although we have a queries module we won't be utilizing it here just yet :)

**Comment by cassio-tav** [comment]
## I know this issue is `on hold`

Nevertheless, @danymat and @vhyrro , I wish to kindly ask you to reconsider, as follows:

### First: Maybe there's a simple way to do it

There are a few Literate Programming Neovim plugins out there. So, one approach would be to look through them and see if any of them could be used with **Neorg**.  And since Neorg is already so powerful and flexible, a minimalist text-code entangler is all that's needed. Well, that minimalist plugin already exists for neovim ─ **ntangle**: [jbyuki/ntangle.nvim](https://github.com/jbyuki/ntangle.nvim). Its syntax is simple and very flexible, in the same spirit of Neorg.

So, maybe it will not be too demanding to create a simple `core.integrations.ntangle` module whose job is just to filter the `*.norg` input files and feed them to ntangle. Just a bit of new syntax would have to be added to Neorg's language, that could go something like this:

#### new syntax:

    @ntangle [<language>] [<namespace>] [<section>]
        <code>
    @end

Where:

+  `<language>` is optional, and it's there just to tell **Neorg** how to highlight the code (the same as with a `@code` block);
+ `<namespace>` specifies a code workspace name (or a [relative] path to a workspace directory);
+ `<section>` specifies the name of (or path to) a source-code file, or the name for a code snippet;
+ `<code>` is the source code in the vanilla `<language>`;
+ The `@ntangle` tag can specify three types of code blocks:
    * a **root section** (this specifies a source-code file to be created) in which case:
       - both the `<namespace>` and the `<section>` arguments are mandatory;
       - `<section>` must have an `=` trailing modifier (this tells ntangle that this is a root section);
    * a **snippet**, in which case:
       - the `<namespace>` argument is not expected;
       - the `<section>` argument is mandatory, and must have either a `+=` or `-=` trailing modifier (these tell ntangle where to insert the snippet;
    * an automatically named single-file application's **root section**, in which case the `<namespace>` argument is mandatory, but `<section>` is not expected;
      
#### Filtered result passed on to ntangle:

###### _Root section_

    ##<namespace>
    @<section>
    <code>    

###### _Code snippet_

    @<section>
    <code>    

###### _Automatically named single-file application's root section_

    ##<namespace>
    @*=
    <code>    
    
#### What will Ntangle do?

Most important, **ntangle** will generate all the source-code files in the appropriate directories (as defined in combination by all the `<namespace>` and `<section>` arguments. But it also generates an HTML file, which is not wanted here, because Neorg already provides a human-readable presentation in a much simpler and user-friendly markup language. 

To be truthful, since I'm not a programmer, I can't be sure that this filter that I propose can be encapsulated in a `core.integrations.ntangle` module, because there are a series of ntangle actions that are of no interest here, e. g., editing, navigating between the tangled and the untangled version of the source files, integration with `treesitter`, etc. Those actions, within Neorg, should be hidden from the UI, and I don't know if a self-contained integrations module can even do that...

Anyway, even if it can't, I think this idea deserves a _**think**_. Because I believe that, if necessary, the ntangle's author [@jbyuki](https://github.com/jbyuki), wouldn't oppose to the idea of providing a flag to disable those functionalities, so that his code may be integrated in such a solid tool as Neorg is. In time, Neorg could come to incorporate a stripped out version of his code, and a future `core.tangle` module could be born.

### Second: Literate Programming needs it

Literate Programming was proposed by Donald Knuth as a way to make code a more human-like symbolic system. I know It doesn't seem to be mainstream (from what I've seen on the Internet). But it also seems that there is a very active community of adepts ─ example: David Wilson's [Literate Configuration Files](https://github.com/daviwil/dotfiles#literate-configuration) (note that it's not markdown, it's `README.org`, and the actual configuration files are generated automatically). Other examples:  [@chayward1's _imutable NixOS configuration_](https://github.com/chayward1/dotfiles#operating-system) and [Jingtao Xu's most interesting _Literate Clojure_](https://github.com/jingtaozf/literate-clojure#introduction).

### Third: well, I need to get rid of Emacs ASAP !

I know I'm of no importance here, but it' true. Emacs is too cumbersome for someone who doesn't need 80% of all the disparate things that it ships with and that one can do with it. Half the time I can't find the commands and functions I need. I want an effective, usable editor; but I need it badly to be a smart one. An editor that enables Literate Programming is indeed a very smart one, one to be proud of.

I'm not a programmer, I'm a teach (mostly of Brazilian Literature). But I'm cursed to be a free-software enthusiast who dares to pay the price of having a Linux-libre desktop with GNU Guix. It's not easy ─ I read a lot of tutorials and scavenge all the `.dotfiles` repositories I can find looking for answers. Regular, normal configuration files won't suffice ─ I need to write detailed, organized plain text explanations on what it does and how I can modify it. Without that, how could I achieve the customization I want, and later understand what it does and how, and why I put it there. I need to make the black-box transparent, so that I can in the future continue to adapt my system to my changing needs. Without that I'm trapped. Free software means that too, right? Control of how the software will satisfy our needs?  Well, Literate Programming can do that for me.

With that said, I need something like Org Mode in order to manage a bunch of `.dotfiles`, as well as my GNU Guix `config.scm` and `manifest.scm` files. So, It's exactly because I'm not a programmer that I need Literate Programming. And I searched GitHub and GitLab, and found many people (actually, mostly programmers), using emacs' org mode to manage configuration files, just as I'm struggling to do. Like David Wilson, whom I linked above.

So, again, given the reach this feature can have, I want to ask you guys to reconsider the `on hold` status. It's worth the effort to achieve even some resemblance of Donald Knuth's Literate Programming ideals. I urge you, then, to rescue me from Emacs ;)

To close, I quote from Neorg‘s README.md:

> ## Why do we need Neorg?
>
>There are currently projects designed to [clone org-mode from emacs](https://github.com/kristijanhusak/orgmode.nvim), then what is the goal of this project?
>
>Whilst those projects are amazing, it's simply not enough for us. _We need our own, *better* solution - one that *will surpass every other text editor*_. It's through our frustration of no native solution for Neovim and inconsistencies in the most popular markup formats that Neorg was born.

**Comment by vhyrro** [comment]
Maan I'm so sorry @cassio-tav for not responding any earlier! I read your incredible message but then promptly forgot about it for some unknown reason, I'm really sorry for that.

Thank you so much for your message! Like, seriously, thank you. Integrating with `ntangle` would be great, but it seems like a lot of work for what we want to do. As a last feature before 0.1 release we'll implement some native and basic tangling support - won't take long (will actually take less time than supporting ntangle's syntax lol), couple of days at most. As of now though I'm busy with writing Neorg's specification and also figuring out the exporter module.

After the basics of tangling are figured out 0.2 will see the rise of a more sophisticated tangling system, including code block execution along the lines of sniprun and all the other org-babel-like goodies. The basic tangling will do what you want - take code blocks, spit them out in a desired location. So there's a lot to look forward to!

I understand that there are people not wanting to use emacs, and I wish I could dedicate as much time as humanly possible in order to advance the project faster, but unfortunately time is my only limiting factor here. I'll try my best though! You'll get your tangling support in Neorg's first release :)

**Comment by cassio-tav** [comment]
Wow, @vhyrro! I did not expect such a warm reception of my request! I'm very honored by your response, thank you. And I'm happy that new functionality is coming.

Sorry for a so long delayed reply, but things are very hectic here for teachers trying to catch up with the school-year calendar after all the pandemics-motivated lockdowns...

Cássio

**Comment by enderger** [comment]
For now, a strong stand-alone tool is <https://github.com/driusan/lmt>. It adds literate programming support for Markdown and works reasonably well ([my dotfiles](https://man.sr.ht/~hutzdog/Dotfiles) make use of it currently, since I found Org-mode too incompatible even if I often use EMACS for writing them).

**Comment by vhyrro** [comment]
Aand it's here! https://github.com/nvim-neorg/neorg/pull/485. If you have an ideas or bugs then don't hesitate to make an issue about it :)

I'm going on holiday for a week so I'm sorry if I don't respond during that time period. I'll keep this issue open for a bit longer until I implement some more features into the tangler, namely directory export instead of single-file export.

**Comment by LamprosPitsillos** [comment]
Woww amazing have a nice holiday vhyrro! Will test it thoroughly!

**Comment by max397574** [comment]
Just ported my init.lua file to neorg
it works and looks amazing

![Screenshot 2022-06-25 at 15 32 33](https://user-images.githubusercontent.com/81827001/175775798-59668502-71e2-4df5-8a36-e6b77770b4fd.png)

**Comment by danymat** [comment]
Closing this as feature is done. Feel free to check https://github.com/nvim-neorg/neorg/wiki/Tangling for more details.

**Comment by egolep** [comment]
Sorry to necropost, but this is the only place where I read about a feature I'm curious about: since now `ntangle` is available, is already possible to also include code block execution results? Or is it still an unimplemented feature, planned for the future?
